### ISSUE TITLE
Initial Predefined ObjectPointers

### ISSUE THREAD

**Issue by acf** [iamleeg/Amiga-Smalltalk#24]
Was running into a few weird things while working on the VM snapshot.  All the guaranteed pointers were returning 456 words for their size bits when I suspect that should be just two - the header (size bits and class pointer).

I propose to add 
  `ObjectMemory_sizeBitsOf_put(objectPointer, HeaderSize);`
to
   https://github.com/iamleeg/Amiga-Smalltalk/blob/master/ObjectMemory.c#L27

But it makes me wonder if there's more we need to do with the initial object pointers to make them behave normally.  snapshot is a unique situation I guess where we wish to inspect details of those "objects" rather than just use them as class pointers in other objects. 🤔 

Figured I'd post the question here in case I was missing something.

**Comment by iamleeg** [comment]
You're right to set the size of those objects correctly in `ObjectMemory_new`. However, isn't the size of the object _in the snapshot_ coming from the snapshot? If I'm misunderstanding, and loading the snapshot doesn't set that size (or you're describing something that happens before the size is overwritten), then no problem. Else there's a question of _why_ the size is 456 in the snapshot.

**Comment by acf** [comment]
I am saving first :-). https://github.com/iamleeg/Amiga-Smalltalk/blob/acf/snapshots/ObjectMemory_Snapshot.c#L86-L103.  given my little snapshot main just does an `ObjectMemory_new` and then saves, all that's there is the predefined pointers.  I did wonder, since they are "constant" whether it was worth saving them or not, but the dbanay code that reads old images *does* so I figured I'd do that too. 

When I save those objects each one seems to report 456 words for the size bits and my code duly goes and fetches each word (seemingly random content) and writes to file.

NB not great code yet, just feeling my way so I can inspect the resultant files and have some confidence I'm doing it right.  I tried to paste the dbanay code and translate from C++ to C without grokking and it went bad so this is a step at a time :-)

**Comment by acf** [comment]
Update, I am writing an image \o/ and the layout certainly matches the format here ( http://www.wolczko.com/st80/ see virtual image tape link near the bottom and the booklet link beside it).  Looking at the contents of that file though the first few objects (which we would assume to be standard 2-52) look a little different.

The way the format works here is at position 512 we start dumping objects. the first 16bits is size (so the 0002 looks right and is what we currently now have for everything).  The second 16 bits is the class pointer which we currently always have blank for the first 2-52.  In the actual image (screenshot) they have a value for the class pointer and some of the objects have a size > 2.  When the size is more than 2 (size+class) the additional words follow.

<img width="459" alt="Screenshot 2020-12-14 at 23 21 03" src="https://user-images.githubusercontent.com/218/102147842-54c7d980-3e63-11eb-96ac-75261c17a9e4.png">

So, I'll press on with loading the image I saved, but I'm not sure what happens when we load this image.  There might but not be enough of the implementation done yet to load a "real" image.  I see (for example) selector names in the image.

<img width="694" alt="Screenshot 2020-12-14 at 23 25 35" src="https://user-images.githubusercontent.com/218/102148118-c738b980-3e63-11eb-811c-4670fbb5d3e7.png">

**Comment by iamleeg** [comment]
I expect the differences you're seeing come down to those objects having real implementations (on the Smalltalk side) in an actual image, thus taking up different memory, having real superclass associations etc. The VM mostly ignores that and either does constant comparisons with a class object pointer, or hopes that the object it sees has the correct memory layout ignoring the Smalltalk metadata, so I/we haven't needed to populate them correctly.

**Comment by acf** [comment]
Yup, that's what I figured.  End result, doubt I can read in the "real" image yet.  But if I can get a load working, and then make a few (say) LargeIntegers and successfully save and load those, I'd feel confident in the save/load mechanism being able to pull in a real image once we can support it.

**Comment by iamleeg** [comment]
Thanks for working on it! And sorry I've been absent from the project, I've had not much time and not much head space these last few months.

**Comment by acf** [comment]
Me neither :-). I just suddenly decided to get back on the saddle. Hope my various questions are not too dumb and/or annoying.  There are parts of what this project that I understand pretty well and parts where I confess I'm just sort of cargo culting 😂   So I'm occasionally in the situation of asking questions like the initial size setting.  I can't always tell what's a conscious decision and what's just not done yet.

**Comment by acf** [comment]
So spent a bunch of time trying to track down weird behaviour with a save->load->save test.  What I'm finally observing is that as I loop through the objects loading them, when I set the size bits for (eg) OOP(N) to `2`, it somehow overwrites the count bits for OOP(N-1) leaving it as 0. so I end up with a corrupt object table.  Cant see why its happening yet but I'll throw away all my debug stuff and try and write a test to demonstrate the issue.... :-/

**Comment by iamleeg** [comment]
Ah interesting. I've seen…not that certainly, but other "when I do something unrelated this memory changes" behaviour. My trick was, having loaded the process in gdb:

 - break at the start of the test
 - set a watchpoint on the object header for OOP(N-1)
 - backtrace whenever that watchpoint is hit

I don't know that m68k has watchpoints, so you might have to either get creative with a monitor or do this on Linux. BTW the size is in the heap space and the count is in the object table so this isn't just "we're off by one writing this word".

**Comment by acf** [comment]
I'm hoping to get to the bottom of it over the holidays.  I'm glad I finally tracked it down.  I was printing the values as I was setting them and they looked fine so I was confused about where it went wrong.  So many printf statements later..... :-)

**Comment by acf** [comment]
Notes more for my own benefit than anything else...

<img width="597" alt="Screenshot 2020-12-20 at 20 20 11" src="https://user-images.githubusercontent.com/218/102723585-e40c3b80-4300-11eb-89b1-4bd68a58636b.png">
<img width="306" alt="Screenshot 2020-12-20 at 20 20 43" src="https://user-images.githubusercontent.com/218/102723588-e7072c00-4300-11eb-9b5b-004de38be17c.png">


Increasingly convinced the predefined pointers are just not properly managed.  Like maybe their OT entries just don't exist or something because they are not going through the same creation mechanism.  I don't see any magic code in the dbanay version but it also seems to assume you always load an image, which one would assume "fills out" 2-52 properly and just uses the constants as well-known references rather than try to populate them properly in ObjectMemory_new.

Will do more digging but I'm happier now its not something inherent in my snapshot code.  To confirm that I might adjust the snapshot code to only save and load OOPs > 52, then allocate a couple of LargeIntegers or something snd check they can be loaded and saved properly.

**Comment by iamleeg** [comment]
That sounds right. I doubt anyone ever bootstrapped a Smalltalk-80, because they made it by modifying Smalltalk-76 until it looked like Smalltalk-80. There always was an image, and those constants in the VM represent the values of objects that had already been made and stored in the image.

The one place where that might not apply is GNU smalltalk which doesn't need to load an image on launch.

**Comment by acf** [comment]
Aha, maybe I'll go look there and see how they set up the "first 52" as I'll henceforth call them.

**Comment by acf** [comment]
Maybe not.  I can't make head nor tail of the repo.  I do see a LOT of smalltalk code so maybe the C part is super minimal..

**Comment by acf** [comment]
so, in the end, I think my snapshot code is right.  I can load the original image just fine and the numbers make sense, no overwriting previous entries.

I'll tidy it up and it could be committed, even though there's little we could do with it just now.

**Comment by iamleeg** [comment]
Yes, please! It'll be useful to motivate completion of the VM if we know that implementing these _x_ byte codes allow us to run these _y_ instructions of the image.

**Comment by acf** [comment]
I just spotted this, apologies for the delay.

**Comment by acf** [comment]
see https://github.com/iamleeg/Amiga-Smalltalk/pull/25
