### ISSUE TITLE
How to help?

### ISSUE THREAD

**Issue by acf** [iamleeg/Amiga-Smalltalk#5]
I'm pretty close to getting my actual Amiga 🤞 and I think I've all but given up on the nostalgia of DICE and will focus on vbcc/amake which is at least maintained.  Given that the way you are working just now is to basically work your way through the blue book and add stuff, it doesn't feel like there's an obvious place to start contributing more than the bits and pieces of compiler soothing I've been doing.

Thought appreciated on if, and how, there's anything else I could be doing beyond just providing an additional "it works on my machine/compiler/environment" (which I'm more then happy to do).

**Comment by iamleeg** [comment]
I’ll break some of these out into separate issues later, or feel free to extract one and claim it if you want to work on it.

 - test the GC. I don’t think garbage collection is well covered by tests, and that would be beneficial.
 - improve compatibility with the ST-80 images. I’ve made some arbitrary choices over things like the identity of some classes, and I bet there are places where the blue book diverges from a real implementation.
 - implement bytecodes. You can probably guess that I’m working through the interpreter specification in order, so if you start somewhere else we won’t conflict.
 - implement primitive methods. See above.
 - native UI. I kind of imagine Transcript being able to write native Intuition text to an Intuition window, and BitBlt drawing to a window or screen, but won’t work on it soon. A stretch goal is BOOPSI wrapper classes so you can do fully native UI from Smalltalk, like the [ObjC wrapper in MorphOS](https://morphos-team.net/guide/objective-c).
 - test/improve native Amiga compatibility. If anything doesn’t work on an A1000 with earliest kickstart, or PPC running MorphOS, we should fix it.
 - image loading. I don’t think the blue book actually describes the image file format?
 - file access, so the VM can fileout/filein to AmigaDOS files.

I think anything else probably depends on having a running VM, which is still a way off.

**Comment by iamleeg** [comment]
Apart from the bit about making bytecodes and primitive methods, which is too much work to be one(two) issue(s) and too much typing to be hundreds of separate issues, I've created separate issues for these tasks.
